# Generated by Django 4.2.7 on 2025-09-30 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('contact_received', 'Contact Message Received'), ('contact_replied', 'Contact Message Replied'), ('song_uploaded', 'Song Uploaded'), ('song_approved', 'Song Approved'), ('song_rejected', 'Song Rejected'), ('payment_received', 'Payment Received'), ('user_registered', 'User Registered'), ('admin_alert', 'Admin Alert'), ('system_maintenance', 'System Maintenance'), ('welcome_message', 'Welcome Message')], max_length=30)),
                ('title_template', models.CharField(help_text='Title template with placeholders', max_length=200)),
                ('message_template', models.TextField(help_text='Message template with placeholders')),
                ('action_url_template', models.CharField(blank=True, max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('expires_in_minutes', models.PositiveIntegerField(default=1440, help_text='Expiry time in minutes (default 24 hours)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_websocket', models.BooleanField(default=True)),
                ('enable_browser_push', models.BooleanField(default=False)),
                ('contact_notifications', models.BooleanField(default=True)),
                ('song_notifications', models.BooleanField(default=True)),
                ('payment_notifications', models.BooleanField(default=True)),
                ('admin_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('enable_quiet_hours', models.BooleanField(default=False)),
                ('quiet_start_time', models.TimeField(default='22:00')),
                ('quiet_end_time', models.TimeField(default='08:00')),
                ('push_endpoint', models.TextField(blank=True, null=True)),
                ('push_p256dh', models.TextField(blank=True, null=True)),
                ('push_auth', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='RealtimeNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('contact_received', 'Contact Message Received'), ('contact_replied', 'Contact Message Replied'), ('song_uploaded', 'Song Uploaded'), ('song_approved', 'Song Approved'), ('song_rejected', 'Song Rejected'), ('payment_received', 'Payment Received'), ('user_registered', 'User Registered'), ('admin_alert', 'Admin Alert'), ('system_maintenance', 'System Maintenance'), ('welcome_message', 'Welcome Message')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.URLField(blank=True, help_text='URL for notification action', null=True)),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification expiry time', null=True)),
                ('channel_name', models.CharField(blank=True, help_text='WebSocket channel name', max_length=100, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_realtime_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'realtime_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='realtime_no_recipie_f70f11_idx'), models.Index(fields=['notification_type', 'priority'], name='realtime_no_notific_604431_idx'), models.Index(fields=['created_at'], name='realtime_no_created_ce4c80_idx')],
            },
        ),
    ]
