# Generated by Django 4.2.7 on 2025-10-03 10:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.apps.referrals.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0004_album_albumtrack_album_albums_artist__d7bb5b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=src.apps.referrals.models.generate_referral_code, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('signups', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_referrals', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_codes',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed_up', 'Signed Up'), ('paid', 'Paid'), ('credit_awarded', 'Credit Awarded')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('tracking_cookie', models.CharField(blank=True, max_length=100, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('signed_up_at', models.DateTimeField(blank=True, null=True)),
                ('first_payment_at', models.DateTimeField(blank=True, null=True)),
                ('credit_awarded_at', models.DateTimeField(blank=True, null=True)),
                ('first_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.referralcode')),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=1, help_text='Number of free uploads', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('used', 'Used'), ('expired', 'Expired')], default='available', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('earned_from_referrals', models.ManyToManyField(blank=True, related_name='credits_awarded', to='referrals.referral')),
                ('used_for_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_credits_used', to='songs.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_credits',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='referral_cr_user_id_31d62a_idx'), models.Index(fields=['status', '-earned_at'], name='referral_cr_status_e8ffd0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='referral_co_code_0cdd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['user', 'is_active'], name='referral_co_user_id_463282_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code', 'status'], name='referrals_referra_36db68_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred_user'], name='referrals_referre_ebd676_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['tracking_cookie'], name='referrals_trackin_35627d_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['-clicked_at'], name='referrals_clicked_0e61be_idx'),
        ),
    ]
