# Generated by Django 4.2.7 on 2025-09-30 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Contact's full name", max_length=255)),
                ('email', models.EmailField(help_text="Contact's email address", max_length=254)),
                ('subject', models.CharField(help_text='Message subject', max_length=255)),
                ('category', models.CharField(choices=[('technical', 'Technical Support'), ('billing', 'Billing & Payments'), ('distribution', 'Music Distribution'), ('royalties', 'Royalties & Analytics'), ('account', 'Account Issues'), ('partnership', 'Partnership Inquiry'), ('general', 'General Inquiry'), ('other', 'Other')], default='general', help_text='Message category', max_length=20)),
                ('message', models.TextField(help_text='The contact message')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('in_progress', 'In Progress'), ('responded', 'Responded'), ('resolved', 'Resolved')], default='new', help_text='Current status of the message', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Message priority level', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When message was first read', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When response was sent', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Sender's IP address", null=True)),
                ('user_agent', models.TextField(blank=True, help_text="Sender's browser information", null=True)),
                ('referrer', models.URLField(blank=True, help_text='Page that referred to contact form', null=True)),
                ('related_ticket', models.ForeignKey(blank=True, help_text='Related support ticket (if created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_message', to='support.ticket')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user account (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='support_con_status_cb8a63_idx'), models.Index(fields=['category', 'priority'], name='support_con_categor_54252f_idx'), models.Index(fields=['email'], name='support_con_email_b616c4_idx')],
            },
        ),
    ]
