import sqlite3
conn = sqlite3.connect('db.sqlite3')
cursor = conn.cursor()
cursor.execute('SELECT name FROM sqlite_master WHERE type="table" AND name LIKE "payment%"')
tables = cursor.fetchall()
print('Payment tables in SQLite:', tables)
cursor.execute('SELECT name FROM sqlite_master WHERE type="table"')
all_tables = cursor.fetchall()
print('All tables in SQLite:', [t[0] for t in all_tables])
conn.close()
