# Generated by Django 5.2.5 on 2025-08-30 04:39

import django.db.models.deletion
import src.apps.songs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # This migration was simplified to avoid conflicts
        # All necessary model changes are already in the initial migration
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='songdistribution',
            options={},
        ),
    ]
