# Generated by Django 5.2.5 on 2025-09-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_platform_options_and_more'),
        ('songs', '0002_fixed_migration'),
    ]

    operations = [
    ]
