# Generated by Django 4.2.7 on 2025-10-03 10:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.apps.songs.album_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0003_merge_20250909_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('release_type', models.CharField(choices=[('single', 'Single'), ('ep', 'EP'), ('album', 'Album')], default='album', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to=src.apps.songs.album_models.album_cover_upload_path)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('number_of_tracks', models.PositiveIntegerField(help_text='Total number of tracks planned for this release', validators=[django.core.validators.MinValueValidator(1)])),
                ('tracks_uploaded', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField(help_text='Scheduled or actual release date')),
                ('is_explicit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('pending', 'Pending Review'), ('scheduled', 'Scheduled'), ('approved', 'Approved'), ('distributed', 'Distributed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notified_scheduled', models.BooleanField(default=False, help_text='Has admin been notified about scheduled release?')),
                ('admin_notified_days', models.JSONField(default=list, help_text='Days before release admin was notified')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='songs.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_membership', to='songs.song')),
            ],
            options={
                'db_table': 'album_tracks',
                'ordering': ['track_number'],
                'indexes': [models.Index(fields=['album', 'track_number'], name='album_track_album_i_4701e4_idx')],
                'unique_together': {('album', 'track_number')},
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', 'status'], name='albums_artist__d7bb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['release_date'], name='albums_release_27939f_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['status', 'release_date'], name='albums_status_127426_idx'),
        ),
    ]
