# Generated by Django 4.2.7 on 2025-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_album_albumtrack_album_albums_artist__d7bb5b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('distributed', 'Distributed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
