# Generated by Django 4.2.7 on 2025-10-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_change_default_status_to_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='share_slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug for public sharing', max_length=255, null=True, unique=True),
        ),
    ]
